### ISSUE TITLE
Excel import

### ISSUE THREAD

**Issue by URI3L-23** [tkallsen/simplescoring-ipsc-support#1]
I like your App a lot. 
Could you please add an excel import for adding shooters faster? Would be awesome

Thanks a lot

**Comment by tkallsen** [comment]
Hi, could you elaborate on this requirement. Are you using the app for bigger matches where you need to import larger amount of users?

**Comment by URI3L-23** [comment]
HiThank you for your answer. We are a fast growing IPSC Airsoft Club. Right now we have about 25 Members and still getting more. We are using your app on Android and on iphone. We would like to import the shooters with an excel sheet which will be auto-created with those members who accept the IPSC training session. Otherwise would be a solution to save all shooters in the app and select the participating people, so only once a time it is recommended to write all the names. Thank you very muchGreetings HeikoP.S.: you could send me your PayPal address so we will send you a pitcher of coffee 😉👌🏼Gesendet mit der GMX Mail AppAm 09.06.23 um 08:42 schrieb Tomas Källsen
                
            
            
                
                    Von: "Tomas Källsen" ***@***.***>Datum: 9. Juni 2023An: "tkallsen/simplescoring-ipsc-support" ***@***.***>Cc: "URI3L-23" ***@***.***>,"Author" ***@***.***>Betreff: Re: [tkallsen/simplescoring-ipsc-support] Excel import (Issue #1)
                
                
Hi, could you elaborate on this requirement. Are you using the app for bigger matches where you need to import larger amount of users?

**Comment by tkallsen** [comment]
The newest version (1.5.4, out now) has the option to clone a session, which will copy all shooters and stages. You could create a session with all the shooters and then clone this whenever you have a training session (and remove non-participants).
