### ISSUE TITLE
SRA target support

### ISSUE THREAD

**Issue by steeriks** [tkallsen/simplescoring-ipsc-support#4]
Would it be possible to add scoring possibilities for SRA?

A-zone 5p
B-zone 5p
C-zone 3p
D-zone 1p
Steel 5p
No shoot -10p
Penalty -10

**Comment by tkallsen** [comment]
Will be possible with new scoring scheme functionality, coming in the next version.

**Comment by tkallsen** [comment]
Resolved in version 1.8

**Comment by steeriks** [comment]
Tjena,Bra jobbat. Det ser mycket lovande ut 👌MvhStefan Eriksson On 27 Mar 2024, at 15:33, Tomas Källsen ***@***.***> wrote:﻿
Resolved in version 1.8
