### ISSUE TITLE
Scoring options.

### ISSUE THREAD

**Issue by TonyRaffelsen** [tkallsen/simplescoring-ipsc-support#6]
I shoot in both ipsc and Norwegian reservist associtation(NROF), where the rules for scoreing are diffrent. They Are not point based there, but you Get time added for hits outside the «a» zone. So a would be 0 added, «b» would be +1 secounds, and «c» would be +3 secounds. Miss is +10 secounds, no shoots +10 secounds and procedure +10. 

Would this be possible to implement?

**Comment by tkallsen** [comment]
Hi Tony,

unfortunately that would be a pretty big rebuild of the entire application, which is not something that I feel that I have the time to undertake. Many parts of the the app depends on a hit factor scoring result.
