### ISSUE TITLE
Hitfaktor för hela matchen

### ISSUE THREAD

**Issue by steeriks** [tkallsen/simplescoring-ipsc-support#7]
Skulle det vara möjligt att implementera så att man kan se hitfaktor för hela "matchen" när man exporterar till excel eller pdf-format. Nu ser man hitfaktor för varje station/person. Men det skulle vra användbart att få hitfaktor presenterat för matchen/person. Speciellt användbart vid kompetensprov för SRA (då flera stationer ingår i kompetensprovet) Nu måste man räkna detta manuellt ;-)

**Comment by tkallsen** [comment]
Added in version 1.8.3.
