### ISSUE TITLE
Disappearing info

### ISSUE THREAD

**Issue by peterrinaldi** [tkallsen/simplescoring-ipsc-support#9]
I have the app on my Android S21 and After I have loaded all the information including Shooters and stage designs, The stages disappear when I next go to the app

**Comment by tkallsen** [comment]
Is this during the same session, or has SimpleScoring IPSC automatically switched to a new session? (will be done if you start the application on new day). You can find your sessions at the bottom of the "Setup"-tab.

If you want to reuse shooters/stages between sessions you can save them as template shooters/stages under the overflow menu (... symbol), which will then be available using Quick Add. You can also copy an entire session, which will clone everything but the stage results.

**Comment by peterrinaldi** [comment]
Thank you for your immediate
Response. Yes I set it up before shooting day. Switch my phone off. Next day I go to it and the stages have disappeared. It appears I will have to do it on the day. Lastly I tried to load it on my iPad but it says I need to update it, but it cannot update. Do u have an earlier version to run on 10.3.4

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tkallsen** [comment]
You can easily switch to the previous session and ignore the new one that was auto-created. Just press "Switch to" on the session where you added your shooters/stages.

Unfortunately the underlying framework that I use only supports more current versions of iOS. The Apple App Store doesn't support distributing previous versions of the same app.

**Comment by peterrinaldi** [comment]
Saving them as templates seems to work om my Samsung S21

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tkallsen** [comment]
Perfect!
